@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

' 訪問者
[利用者] o-- [会員番号]
[利用者] o-- [氏名]
[利用者] o-- [メール]
[利用者] o-- [上限冊数]
[利用者] o-- [貸し出し期間]
[利用者] o-- [書籍・雑誌]
[利用者] o-- [管理番号]
[利用者] o-- [学生]
[利用者] o-- [職員]

[会員番号] o--[学生番号]
[会員番号] o--[職員番号]

[学生] o--[学生証]

[職員] o--[職員証]





@enduml